#
# Makefile for the Linux/AVR32 kernel.
#

extra-y				:= head.o vmlinux.lds


obj-y	                        += entry.o memreg.o
obj-y				+= syscall_table.o syscall-stubs.o irq.o
obj-y				+= setup.o ptrace.o traps.o
obj-y				+= signal.o sys_zpu.o process.o time.o
obj-y				+= init_task.o switch_to.o cpu.o
